// sport_disciplines_data.dart

class SportDisciplines {
  static final Map<String, List<Map<String, String>>> disciplines = {
    'General Fitness': [
      {'name': 'Strength Training', 'gender': 'Men'},
      {'name': 'Strength Training', 'gender': 'Women'},
      {'name': 'Cardio Training', 'gender': 'Men'},
      {'name': 'Cardio Training', 'gender': 'Women'},
      {'name': 'CrossFit', 'gender': 'Men'},
      {'name': 'CrossFit', 'gender': 'Women'},
      {'name': 'Bodybuilding', 'gender': 'Men'},
      {'name': 'Bodybuilding', 'gender': 'Women'},
    ],
    'Archery': [
      {'name': 'Recurve', 'gender': 'Men'},
      {'name': 'Recurve', 'gender': 'Women'},
      {'name': 'Compound', 'gender': 'Men'},
      {'name': 'Compound', 'gender': 'Women'},
      {'name': 'Barebow', 'gender': 'Men'},
      {'name': 'Barebow', 'gender': 'Women'},
    ],
    'Badminton': [
      {'name': 'Singles', 'gender': 'Men'},
      {'name': 'Singles', 'gender': 'Women'},
      {'name': 'Doubles', 'gender': 'Men'},
      {'name': 'Doubles', 'gender': 'Women'},
      {'name': 'Mixed Doubles', 'gender': 'Mixed'},
    ],
    'Ballet': [
      {'name': 'Classical Ballet', 'gender': 'Men'},
      {'name': 'Classical Ballet', 'gender': 'Women'},
      {'name': 'Contemporary Ballet', 'gender': 'Men'},
      {'name': 'Contemporary Ballet', 'gender': 'Women'},
      {'name': 'Neoclassical Ballet', 'gender': 'Men'},
      {'name': 'Neoclassical Ballet', 'gender': 'Women'},
    ],
    'Baseball': [
      {'name': 'Pitcher', 'gender': 'Men'},
      {'name': 'Catcher', 'gender': 'Men'},
      {'name': 'Infielder', 'gender': 'Men'},
      {'name': 'Outfielder', 'gender': 'Men'},
      {'name': 'Softball Pitcher', 'gender': 'Women'},
      {'name': 'Softball Catcher', 'gender': 'Women'},
      {'name': 'Softball Infielder', 'gender': 'Women'},
      {'name': 'Softball Outfielder', 'gender': 'Women'},
    ],
    'Basketball': [
      {'name': 'Point Guard', 'gender': 'Men'},
      {'name': 'Point Guard', 'gender': 'Women'},
      {'name': 'Shooting Guard', 'gender': 'Men'},
      {'name': 'Shooting Guard', 'gender': 'Women'},
      {'name': 'Small Forward', 'gender': 'Men'},
      {'name': 'Small Forward', 'gender': 'Women'},
      {'name': 'Power Forward', 'gender': 'Men'},
      {'name': 'Power Forward', 'gender': 'Women'},
      {'name': 'Center', 'gender': 'Men'},
      {'name': 'Center', 'gender': 'Women'},
      {'name': '3x3 Basketball', 'gender': 'Men'},
      {'name': '3x3 Basketball', 'gender': 'Women'},
    ],
    'Bowling': [
      {'name': 'Ten-pin', 'gender': 'Men'},
      {'name': 'Ten-pin', 'gender': 'Women'},
      {'name': 'Nine-pin', 'gender': 'Men'},
      {'name': 'Nine-pin', 'gender': 'Women'},
    ],
    'Boxing': [
      {'name': 'Flyweight', 'gender': 'Men'},
      {'name': 'Flyweight', 'gender': 'Women'},
      {'name': 'Bantamweight', 'gender': 'Men'},
      {'name': 'Bantamweight', 'gender': 'Women'},
      {'name': 'Featherweight', 'gender': 'Men'},
      {'name': 'Featherweight', 'gender': 'Women'},
      {'name': 'Lightweight', 'gender': 'Men'},
      {'name': 'Lightweight', 'gender': 'Women'},
      {'name': 'Welterweight', 'gender': 'Men'},
      {'name': 'Welterweight', 'gender': 'Women'},
      {'name': 'Middleweight', 'gender': 'Men'},
      {'name': 'Middleweight', 'gender': 'Women'},
      {'name': 'Light Heavyweight', 'gender': 'Men'},
      {'name': 'Light Heavyweight', 'gender': 'Women'},
      {'name': 'Heavyweight', 'gender': 'Men'},
      {'name': 'Heavyweight', 'gender': 'Women'},
    ],
    'Calisthenics': [
      {'name': 'Street Workout', 'gender': 'Men'},
      {'name': 'Street Workout', 'gender': 'Women'},
      {'name': 'Freestyle', 'gender': 'Men'},
      {'name': 'Freestyle', 'gender': 'Women'},
      {'name': 'Static Holds', 'gender': 'Men'},
      {'name': 'Static Holds', 'gender': 'Women'},
    ],
    'Cheerleading': [
      {'name': 'All Star', 'gender': 'Women'},
      {'name': 'All Star', 'gender': 'Men'},
      {'name': 'School/College', 'gender': 'Women'},
      {'name': 'School/College', 'gender': 'Men'},
      {'name': 'Stunts', 'gender': 'Women'},
      {'name': 'Stunts', 'gender': 'Men'},
      {'name': 'Tumbling', 'gender': 'Women'},
      {'name': 'Tumbling', 'gender': 'Men'},
    ],
    'Cycling': [
      {'name': 'Road Racing', 'gender': 'Men'},
      {'name': 'Road Racing', 'gender': 'Women'},
      {'name': 'Track Cycling', 'gender': 'Men'},
      {'name': 'Track Cycling', 'gender': 'Women'},
      {'name': 'Mountain Biking', 'gender': 'Men'},
      {'name': 'Mountain Biking', 'gender': 'Women'},
      {'name': 'BMX Racing', 'gender': 'Men'},
      {'name': 'BMX Racing', 'gender': 'Women'},
      {'name': 'Cyclo-cross', 'gender': 'Men'},
      {'name': 'Cyclo-cross', 'gender': 'Women'},
      {'name': 'Time Trial', 'gender': 'Men'},
      {'name': 'Time Trial', 'gender': 'Women'},
    ],
    'Dance': [
      {'name': 'Hip Hop', 'gender': 'Men'},
      {'name': 'Hip Hop', 'gender': 'Women'},
      {'name': 'Contemporary', 'gender': 'Men'},
      {'name': 'Contemporary', 'gender': 'Women'},
      {'name': 'Jazz', 'gender': 'Men'},
      {'name': 'Jazz', 'gender': 'Women'},
      {'name': 'Ballroom', 'gender': 'Men'},
      {'name': 'Ballroom', 'gender': 'Women'},
      {'name': 'Latin', 'gender': 'Men'},
      {'name': 'Latin', 'gender': 'Women'},
      {'name': 'Breaking', 'gender': 'Men'},
      {'name': 'Breaking', 'gender': 'Women'},
    ],
    'Fencing': [
      {'name': 'Foil', 'gender': 'Men'},
      {'name': 'Foil', 'gender': 'Women'},
      {'name': 'Épée', 'gender': 'Men'},
      {'name': 'Épée', 'gender': 'Women'},
      {'name': 'Sabre', 'gender': 'Men'},
      {'name': 'Sabre', 'gender': 'Women'},
    ],
    'Figure Skating': [
      {'name': 'Singles', 'gender': 'Men'},
      {'name': 'Singles', 'gender': 'Women'},
      {'name': 'Pairs', 'gender': 'Mixed'},
      {'name': 'Ice Dance', 'gender': 'Mixed'},
      {'name': 'Synchronized Skating', 'gender': 'Women'},
      {'name': 'Synchronized Skating', 'gender': 'Men'},
    ],
    'Football': [
      {'name': 'Quarterback', 'gender': 'Men'},
      {'name': 'Running Back', 'gender': 'Men'},
      {'name': 'Wide Receiver', 'gender': 'Men'},
      {'name': 'Offensive Line', 'gender': 'Men'},
      {'name': 'Defensive Line', 'gender': 'Men'},
      {'name': 'Linebacker', 'gender': 'Men'},
      {'name': 'Defensive Back', 'gender': 'Men'},
      {'name': 'Flag Football', 'gender': 'Women'},
      {'name': 'Touch Football', 'gender': 'Women'},
    ],
    'Golf': [
      {'name': 'Stroke Play', 'gender': 'Men'},
      {'name': 'Stroke Play', 'gender': 'Women'},
      {'name': 'Match Play', 'gender': 'Men'},
      {'name': 'Match Play', 'gender': 'Women'},
      {'name': 'Long Drive', 'gender': 'Men'},
      {'name': 'Long Drive', 'gender': 'Women'},
    ],
    'Gymnastics': [
      {'name': 'Artistic - Floor', 'gender': 'Men'},
      {'name': 'Artistic - Floor', 'gender': 'Women'},
      {'name': 'Artistic - Pommel Horse', 'gender': 'Men'},
      {'name': 'Artistic - Balance Beam', 'gender': 'Women'},
      {'name': 'Artistic - Rings', 'gender': 'Men'},
      {'name': 'Artistic - Uneven Bars', 'gender': 'Women'},
      {'name': 'Artistic - Vault', 'gender': 'Men'},
      {'name': 'Artistic - Vault', 'gender': 'Women'},
      {'name': 'Artistic - Parallel Bars', 'gender': 'Men'},
      {'name': 'Artistic - Horizontal Bar', 'gender': 'Men'},
      {'name': 'Rhythmic', 'gender': 'Women'},
      {'name': 'Trampoline', 'gender': 'Men'},
      {'name': 'Trampoline', 'gender': 'Women'},
      {'name': 'Acrobatic', 'gender': 'Men'},
      {'name': 'Acrobatic', 'gender': 'Women'},
    ],
    'Ice Hockey': [
      {'name': 'Forward', 'gender': 'Men'},
      {'name': 'Forward', 'gender': 'Women'},
      {'name': 'Defense', 'gender': 'Men'},
      {'name': 'Defense', 'gender': 'Women'},
      {'name': 'Goaltender', 'gender': 'Men'},
      {'name': 'Goaltender', 'gender': 'Women'},
    ],
    'Martial Arts': [
      {'name': 'Karate', 'gender': 'Men'},
      {'name': 'Karate', 'gender': 'Women'},
      {'name': 'Taekwondo', 'gender': 'Men'},
      {'name': 'Taekwondo', 'gender': 'Women'},
      {'name': 'Judo', 'gender': 'Men'},
      {'name': 'Judo', 'gender': 'Women'},
      {'name': 'Brazilian Jiu-Jitsu', 'gender': 'Men'},
      {'name': 'Brazilian Jiu-Jitsu', 'gender': 'Women'},
      {'name': 'Muay Thai', 'gender': 'Men'},
      {'name': 'Muay Thai', 'gender': 'Women'},
      {'name': 'MMA', 'gender': 'Men'},
      {'name': 'MMA', 'gender': 'Women'},
      {'name': 'Kung Fu', 'gender': 'Men'},
      {'name': 'Kung Fu', 'gender': 'Women'},
    ],
    'Parkour': [
      {'name': 'Speed', 'gender': 'Men'},
      {'name': 'Speed', 'gender': 'Women'},
      {'name': 'Freestyle', 'gender': 'Men'},
      {'name': 'Freestyle', 'gender': 'Women'},
      {'name': 'Skill', 'gender': 'Men'},
      {'name': 'Skill', 'gender': 'Women'},
    ],
    'Rock Climbing': [
      {'name': 'Bouldering', 'gender': 'Men'},
      {'name': 'Bouldering', 'gender': 'Women'},
      {'name': 'Lead Climbing', 'gender': 'Men'},
      {'name': 'Lead Climbing', 'gender': 'Women'},
      {'name': 'Speed Climbing', 'gender': 'Men'},
      {'name': 'Speed Climbing', 'gender': 'Women'},
      {'name': 'Traditional', 'gender': 'Men'},
      {'name': 'Traditional', 'gender': 'Women'},
    ],
    'Rowing': [
      {'name': 'Single Sculls', 'gender': 'Men'},
      {'name': 'Single Sculls', 'gender': 'Women'},
      {'name': 'Double Sculls', 'gender': 'Men'},
      {'name': 'Double Sculls', 'gender': 'Women'},
      {'name': 'Coxless Pair', 'gender': 'Men'},
      {'name': 'Coxless Pair', 'gender': 'Women'},
      {'name': 'Coxless Four', 'gender': 'Men'},
      {'name': 'Coxless Four', 'gender': 'Women'},
      {'name': 'Eight', 'gender': 'Men'},
      {'name': 'Eight', 'gender': 'Women'},
    ],
    'Running': [
      {'name': 'Sprints (100m-400m)', 'gender': 'Men'},
      {'name': 'Sprints (100m-400m)', 'gender': 'Women'},
      {'name': 'Middle Distance (800m-1500m)', 'gender': 'Men'},
      {'name': 'Middle Distance (800m-1500m)', 'gender': 'Women'},
      {'name': 'Long Distance (5k-10k)', 'gender': 'Men'},
      {'name': 'Long Distance (5k-10k)', 'gender': 'Women'},
      {'name': 'Marathon', 'gender': 'Men'},
      {'name': 'Marathon', 'gender': 'Women'},
      {'name': 'Ultra Marathon', 'gender': 'Men'},
      {'name': 'Ultra Marathon', 'gender': 'Women'},
      {'name': 'Trail Running', 'gender': 'Men'},
      {'name': 'Trail Running', 'gender': 'Women'},
      {'name': 'Hurdles', 'gender': 'Men'},
      {'name': 'Hurdles', 'gender': 'Women'},
    ],
    'Skiing': [
      {'name': 'Alpine - Downhill', 'gender': 'Men'},
      {'name': 'Alpine - Downhill', 'gender': 'Women'},
      {'name': 'Alpine - Slalom', 'gender': 'Men'},
      {'name': 'Alpine - Slalom', 'gender': 'Women'},
      {'name': 'Alpine - Giant Slalom', 'gender': 'Men'},
      {'name': 'Alpine - Giant Slalom', 'gender': 'Women'},
      {'name': 'Cross-Country', 'gender': 'Men'},
      {'name': 'Cross-Country', 'gender': 'Women'},
      {'name': 'Freestyle', 'gender': 'Men'},
      {'name': 'Freestyle', 'gender': 'Women'},
      {'name': 'Ski Jumping', 'gender': 'Men'},
      {'name': 'Ski Jumping', 'gender': 'Women'},
    ],
    'Snowboarding': [
      {'name': 'Halfpipe', 'gender': 'Men'},
      {'name': 'Halfpipe', 'gender': 'Women'},
      {'name': 'Slopestyle', 'gender': 'Men'},
      {'name': 'Slopestyle', 'gender': 'Women'},
      {'name': 'Snowboard Cross', 'gender': 'Men'},
      {'name': 'Snowboard Cross', 'gender': 'Women'},
      {'name': 'Alpine', 'gender': 'Men'},
      {'name': 'Alpine', 'gender': 'Women'},
    ],
    'Soccer': [
      {'name': 'Goalkeeper', 'gender': 'Men'},
      {'name': 'Goalkeeper', 'gender': 'Women'},
      {'name': 'Defender', 'gender': 'Men'},
      {'name': 'Defender', 'gender': 'Women'},
      {'name': 'Midfielder', 'gender': 'Men'},
      {'name': 'Midfielder', 'gender': 'Women'},
      {'name': 'Forward', 'gender': 'Men'},
      {'name': 'Forward', 'gender': 'Women'},
      {'name': 'Futsal', 'gender': 'Men'},
      {'name': 'Futsal', 'gender': 'Women'},
    ],
    'Speed Skating': [
      {'name': 'Short Track', 'gender': 'Men'},
      {'name': 'Short Track', 'gender': 'Women'},
      {'name': 'Long Track', 'gender': 'Men'},
      {'name': 'Long Track', 'gender': 'Women'},
      {'name': 'Inline', 'gender': 'Men'},
      {'name': 'Inline', 'gender': 'Women'},
    ],
    'Swimming': [
      {'name': 'Freestyle', 'gender': 'Men'},
      {'name': 'Freestyle', 'gender': 'Women'},
      {'name': 'Backstroke', 'gender': 'Men'},
      {'name': 'Backstroke', 'gender': 'Women'},
      {'name': 'Breaststroke', 'gender': 'Men'},
      {'name': 'Breaststroke', 'gender': 'Women'},
      {'name': 'Butterfly', 'gender': 'Men'},
      {'name': 'Butterfly', 'gender': 'Women'},
      {'name': 'Individual Medley', 'gender': 'Men'},
      {'name': 'Individual Medley', 'gender': 'Women'},
      {'name': 'Open Water', 'gender': 'Men'},
      {'name': 'Open Water', 'gender': 'Women'},
    ],
    'Tennis': [
      {'name': 'Singles', 'gender': 'Men'},
      {'name': 'Singles', 'gender': 'Women'},
      {'name': 'Doubles', 'gender': 'Men'},
      {'name': 'Doubles', 'gender': 'Women'},
      {'name': 'Mixed Doubles', 'gender': 'Mixed'},
    ],
    'Triathlon': [
      {'name': 'Sprint Distance', 'gender': 'Men'},
      {'name': 'Sprint Distance', 'gender': 'Women'},
      {'name': 'Olympic Distance', 'gender': 'Men'},
      {'name': 'Olympic Distance', 'gender': 'Women'},
      {'name': 'Half Ironman', 'gender': 'Men'},
      {'name': 'Half Ironman', 'gender': 'Women'},
      {'name': 'Ironman', 'gender': 'Men'},
      {'name': 'Ironman', 'gender': 'Women'},
    ],
    'Volleyball': [
      {'name': 'Indoor - Outside Hitter', 'gender': 'Men'},
      {'name': 'Indoor - Outside Hitter', 'gender': 'Women'},
      {'name': 'Indoor - Middle Blocker', 'gender': 'Men'},
      {'name': 'Indoor - Middle Blocker', 'gender': 'Women'},
      {'name': 'Indoor - Setter', 'gender': 'Men'},
      {'name': 'Indoor - Setter', 'gender': 'Women'},
      {'name': 'Indoor - Libero', 'gender': 'Men'},
      {'name': 'Indoor - Libero', 'gender': 'Women'},
      {'name': 'Beach Volleyball', 'gender': 'Men'},
      {'name': 'Beach Volleyball', 'gender': 'Women'},
    ],
  };
}