name: peakfit_frontend
description: "PeakFit TRUST"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  cloud_functions: ^5.5.1
  firebase_storage: ^12.0.0

  # UI Components
  sleek_circular_slider: ^2.0.1
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  touchable: ^1.0.2
  flutter_svg: ^2.0.9
  path_parsing: ^1.0.1
  xml: ^6.3.0

  # Media
  video_player: ^2.8.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/skate-montage2.mp4
    - assets/svg/backmuscle-final.svg